title: My Github Projects

url: https://michael-currin.netlify.com/
# Built-in for Github Pages but needed on Netlify.
repository: MichaelCurrin/my-github-projects

theme: jekyll-bulma

collections:
  topics:
    output: true

defaults:
  - scope:
      path: "_topics/*"
    values:
      layout: "topic"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - docs/
  - vendor/
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - Makefile
