title: My Github Projects

url: https://michael-currin.netlify.com/
# Built-in for Github Pages but needed on Netlify.
repository: MichaelCurrin/my-github-projects
twitter_handle: MichaelCurrin

theme: jekyll-bulma

header_pages:
  - all_repos.md
  - all_topics.md
  - about.md

collections:
  topics:
    output: true

exclude:
  - docs/
  - LICENSE
  - README.md
  - Makefile
  - netlify.toml
  - package.json
  - package-lock.json
