title: My Github Projects

url: ""
baseurl: /my-github-projects

collections:
  topics:
    output: true

defaults:
  - scope:
      path: "_topics/*"
    values:
      layout: "topic"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - vendor/
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - Makefile
