title: My GitHub Projects

url: https://michael-currin.netlify.com
baseurl: ""

repository: MichaelCurrin/my-github-projects
twitter_handle: MichaelCurrin

theme: jekyll-bulma

permalink: pretty

header_pages:
  - repos.md
  - topics.md
  - about.md

collections:
  topics:
    output: true

liquid:
  strict_filters: true
  strict_variables: true

exclude:
  - docs/
  - LICENSE
  - README.md
  - Makefile
  - netlify.toml
  - package.json
  - package-lock.json
